source 'https://rubygems.org'

# Specify your gem's dependencies in pipeline-api.gemspec
gemspec

if File.exist? File.expand_path("../../pandora-transport/pandora-transport.gemspec", __FILE__)
  gem 'pandora-transport', :path => File.expand_path("../../pandora-transport", __FILE__), :require => false
end

if File.exist? File.expand_path("../../pipeline/pipeline.gemspec", __FILE__)
  gem 'pipeline', :path => File.expand_path("../../pipeline", __FILE__), :require => false
end
