require "bundler/gem_tasks"

desc "Run unit tests"
task :default => 'test:unit'
task  :test   => 'test:unit'

# ----- Test tasks ------------------------------------------------------------

require 'rake/testtask'
namespace :test do
  task :ci_reporter do
    ENV['CI_REPORTS'] ||= 'tmp/reports'
    if defined?(RUBY_VERSION) && RUBY_VERSION < '1.9'
      require 'ci/reporter/rake/test_unit'
      Rake::Task['ci:setup:testunit'].invoke
    else
      require 'ci/reporter/rake/minitest'
      Rake::Task['ci:setup:minitest'].invoke
    end
  end

  Rake::TestTask.new(:unit) do |test|
    Rake::Task['test:ci_reporter'].invoke if ENV['CI']
    test.libs << 'lib' << 'test'
    test.test_files = FileList["test/unit/**/*_test.rb"]
    # test.verbose = true
    # test.warning = true
  end

  desc "Run unit and integration tests"
  task :all do
    Rake::Task['test:ci_reporter'].invoke if ENV['CI']
    Rake::Task['test:unit'].invoke
  end

  namespace :cluster do
    desc "Start Pipeline nodes for tests"
    task :start do
      $LOAD_PATH << File.expand_path('../../pandora-transport/lib', __FILE__) << File.expand_path('../test', __FILE__)
    end

    desc "Stop Pipeline nodes for tests"
    task :stop do
      $LOAD_PATH << File.expand_path('../../pandora-transport/lib', __FILE__) << File.expand_path('../test', __FILE__)
    end
  end
end

# ----- Documentation tasks ---------------------------------------------------

require 'yard'
YARD::Rake::YardocTask.new(:doc) do |t|
  t.options = %w| --embed-mixins --markup=markdown |
end

# ----- Code analysis tasks ---------------------------------------------------

if defined?(RUBY_VERSION) && RUBY_VERSION > '1.9'
  require 'cane/rake_task'
  Cane::RakeTask.new(:quality) do |cane|
    cane.abc_max = 15
    cane.no_style = true
  end
end
