source 'https://rubygems.org'

# Specify your gem's dependencies in logdb.gemspec
gemspec

if File.exist? File.expand_path("../../pandora-transport/pandora-transport.gemspec", __FILE__)
  gem 'pandora-transport', :path => File.expand_path("../../pandora-transport", __FILE__), :require => false
end

if File.exist? File.expand_path("../../logdb-api/logdb-api.gemspec", __FILE__)
  gem 'logdb-api', :path => File.expand_path("../../logdb-api", __FILE__), :require => false
end
